package ui

// ICONS
const ICON_MIN_SIZE = float32(64)
const ICON_MAX_SIZE = float32(64)

// SONGS
const SONG_LIST_WIDTH = float32(250)
const SONG_LIST_HEIGHT = float32(275)

// SONGS BACKGROUND
const SONG_BACKGROUND_WIDTH = float32(250)
const SONG_BACKGROUND_HEIGHT = float32(275)

// VOLUME
const VOLUME_SLIDER_WIDTH = float32(23)
const VOLUME_SLIDER_HEIGHT = float32(120)

const VOLUME_SLIDER_MIN_DB = float64(-5)
const VOLUME_SLIDER_MAX_DB = float64(0)

// VOLUME BACKGROUND
const SLIDER_RECT_WIDTH = float32(23)
const SLIDER_RECT_HEIGHT = float32(120)

// WINDOW
const WINDOW_WIDTH = float32(900)
const WINDOW_HEIGHT = float32(700)

// BUTTONS
const BUTTON_SIZE = float32(64)
const BUTTON_MARGIN_BOTTOM = float32(10)
const BUTTONS_SPACING = float32(36)
const BUTTON_COUNT = 3
const TOTAL_BUTTONS_WIDTH = BUTTON_SIZE*float32(BUTTON_COUNT) + BUTTONS_SPACING*float32(BUTTON_COUNT-1)
const BUTTON_START_X = (WINDOW_WIDTH - TOTAL_BUTTONS_WIDTH) / 2
const BUTTONS_Y = WINDOW_HEIGHT - BUTTON_SIZE - BUTTON_MARGIN_BOTTOM
const VOLUME_X = WINDOW_WIDTH - 33
const VOLUME_Y = WINDOW_HEIGHT - 120 - 10

// LABELS
const LABELS_HEIGHT = float32(25)
const LABELS_WIDTH = float32(300)
const LABELS_SPACING = float32(4)
const LABEL_BUTTONS_Y = float32(700) - BUTTON_SIZE - BUTTON_MARGIN_BOTTOM
const LABELS_X = (WINDOW_WIDTH-LABELS_WIDTH)/2 + 150

// SEEK
const SEEK_SLIDER_WIDTH = float32(300)
const SEEK_SLIDER_HEIGHT = float32(20)
